<?php
/**
 * 1997-2013 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2013 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    Event.observe('payment_paybox_system_pbx_typepaiement', 'change', function() {
        paymentType = $('<?php echo $this->getParentHtmlId() ?>').value;
        jsonObj = eval('(' + '<?php echo $this->getJsonCartTypes() ?>' + ')');
        option = '';
        if (cartTypes = jsonObj[paymentType]) {
            for (var i in cartTypes) {
                if (i == 'none') {
                    option = option + '<option value="">' + cartTypes[i] + '</option>';
                } else {
                    option = option + '<option value="' + i + '">' + cartTypes[i] + '</option>';
                }
            }
        } else {
            option = '<option value=""></option>';
        }
        $('<?php echo $this->getDependHtmlId() ?>').innerHTML = option;
    });
</script>